### PR TITLE
Fix whitespace-only indentation

### LINKED ISSUE #30: Whitespace-only lines mess with indentation
Hi there, thanks for the great adapter!

I've noticed that if your template or script tag contents contain whitespace-only lines, the entire content gets _indented_ one level further, while the whitespace-only lines themselves get _outdented_ one level back (ie untouched).

After debugging this adapter's code, it's clear that the problem actually lies with [indent-string](https://github.com/sindresorhus/indent-string), which is used by [vue-sfc-descriptor-to-string](https://github.com/psalaets/vue-sfc-descriptor-to-string), and which ignores indenting whitespace-only lines by design...

I've got a fork to get around this here in the adapter code coming!

# Input

```vue
<template>
····<div>
····
········<span />
····</div>
</template>
<script>
····export default {
········name: 'HasWhitespaceLines',
········
········data() {
············return {
················string: `
····················a multi
····················
····················line string
················`
············}
········},
····}
</script>
```

# Actual

```vue
<template>
········<div>
····
············<span />
········</div>
</template>
<script>
········export default {
············name: 'HasWhitespaceLines',
········
············data() {
················return {
····················string: `
························a multi
····················
························line string
····················`
················}
············},
········}
</script>
```

### PR DESCRIPTION
**Pull request by nemoDreamer**
FIXES #30

### CODE REVIEW

File: src/jscodeshift-mode.js [hunk 1]
```diff
@@ -10,12 +12,20 @@ function adapt(transform, settings) {
...
-      fileInfo.source = scriptBlock.content;
+      const newScriptContent = transform(
+        Object.assign({}, fileInfo, {
+          source: scriptBlock.content,
+        }),
+        api,
+        options
+      );
 
-      const newScriptContent = transform(fileInfo, api, options);
```
Comment (nemoDreamer) [inline src/jscodeshift-mode.js:18]: Don't modify passed-in `fileInfo` object.

File: src/parse-sfc.js [hunk 2]
```diff
@@ -22,7 +22,7 @@ module.exports = function parse(source) {
 function detectIndent(sfcBlock, source) {
   const nonEmptyPaddingsPerLine = source.substring(sfcBlock.start, sfcBlock.end)
     .split('\n')
-    .filter(line => line !== '')
+    .filter(line => !line.match(/^\s*$/))
```
Comment (nemoDreamer) [inline src/parse-sfc.js:25]: This was causing the entire block to get indented one extra level when there were whitespace-only lines or mixed tabs.

Now it matches that beginning/end empty lines, but also ignores those other weird cases.

**Comment by psalaets** [comment]
Thanks for investigating and fixing this issue. Your changes went out in `vue-jscodeshift-adapter` version 2.2.1
